# Generated by Django 2.2.1 on 2019-05-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasteapp', '0002_paste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
