# Generated by Django 2.2.1 on 2019-05-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasteapp', '0003_auto_20190523_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='slug',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
