# Generated by Django 2.2.1 on 2019-05-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasteapp', '0004_auto_20190523_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
