# Generated by Django 2.2.1 on 2019-05-23 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasteapp', '0005_paste_encrypted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paste',
            name='encrypted',
        ),
    ]
